# Site settings
title: "Bradford Fults"
description: "Texan sense and charm."
baseurl: ''
url: ''
google_analytics: 'G-10Z97LZD32'
# twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

exclude:
  - assets
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - script/generate-svgs

permalink: "/:categories/:title/"

plugins:
  - jekyll-paginate

paginate: 10

jekyll-typogrify-auto:
  tag_selector: article
